In [2]:
import jovian
import torch

### Tensors
* A tensor is a number, vector, matrix or any n-dimensional array

In [6]:
# number tensor
tensor_1 = torch.tensor(data = 5.0)
tensor_1

tensor(5.)

In [7]:
tensor_1.dtype

torch.float32

In [12]:
# vector tensor
tensor_2 = torch.tensor(data = list(range(1,5)))
tensor_2

tensor([1, 2, 3, 4])

In [13]:
tensor_2.dtype

torch.int64

* Here if the first element is a float, all the elements are converted to float, all the elements can only be of one data type

In [14]:
tensor_2 = torch.tensor(data = [1.0,2,4,5])
tensor_2

tensor([1., 2., 4., 5.])

In [15]:
tensor_2.dtype

torch.float32

In [17]:
# matrix
tensor_3 =  torch.tensor([[1,2.],
                          [3,4],
                          [5,6]])
tensor_3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
# 3 - dimensional array
te